### ISSUE TITLE
Support Concurrency for Add(...), Alter(...), Remove(...), & Register(...).

### ISSUE THREAD

**Issue by fr33r** [freerware/work#25]
**Description**

It may be desirable for consumers of `work` to perform concurrent operations that interact with work units. One such prominent example is for `Register(...)`. `Register(...)` is called during database retrieval operations, and retrieval operations are typically parallelized when there is a lot of data to fetch. 

**Example Usage**

There would be no interface changes. Instead, the data structures used internally would need to support concurrent writes/reads, such as [`sync.Map`](https://golang.org/pkg/sync/#Map). Doing so would allow the following trivial example:

```go
...
var w work.Unit
w = ...
func register(entity interface{}) {
  w.Register(entity)
}
go register(Foo{})
go register(Bar{})
...
```

**Comment by freerjm** [comment]
tackled this in #35 .

**Comment by fr33r** [comment]
Going to reopen this, as the internal implementation should make use of `sync.Map` as suggested. It will simplify existing code by eliminating mutex locking and unlocking code. Unfortunately, it doesn't look like I left any breadcrumbs for me around why I didn't choose that approach in the first place.

**Comment by fr33r** [comment]
Closing in favor of #71 .
